site_name: Tide Docs
site_description: Documentation for the Tide project
site_url: https://example.com
nav:
  - Home: index.md
  - What is Tide?: what-is-tide.md
  - Outline: _outline.md
theme:
  name: material
