[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "breathing-willow"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[project.scripts]
breathing-willow = "cli.breathing_willow:main"
